//! Fuzz target (structured / inverse property): for any structurally-valid
//! event, `parse_revive_event(encode(event)) == Some(event)`. bolero's
//! derived `TypeGenerator` produces only well-formed `EventShape`s, so any
//! deviation is a real decoder regression (wrong field order, dropped
//! padding, mis-decoded epoch), not malformed input.
//!
//! `harness = false` binary. Run with
//! `cargo test --test fuzz_event_round_trip`; deep-fuzz with
//! `cargo bolero test fuzz_event_round_trip --engine libfuzzer`.

use std::panic::AssertUnwindSafe;

use bolero::{TypeGenerator, check};
use on_chain_client::decode::dispatch::{PASEO_AH_SPEC_VERSION, for_runtime};
use on_chain_client::{Epoch, Event, OnChainRootHash, OrgAdmin, OrgPubKey};

#[path = "../fuzz_support/mod.rs"]
mod support;

use support::{encode_contract_emitted, padded_address, sig_genesis, sig_root_updated, uint256_be};

/// A structurally-valid event. bolero fills every field with generated bytes;
/// the variants mirror the two Solidity events the decoder understands.
#[derive(Debug, Clone, TypeGenerator)]
enum EventShape {
    Genesis {
        contract: [u8; 20],
        admin: [u8; 20],
        root: [u8; 32],
        key: [u8; 32],
    },
    Update {
        contract: [u8; 20],
        admin: [u8; 20],
        epoch: u64,
        root: [u8; 32],
        key: [u8; 32],
        prev_root: [u8; 32],
    },
}

/// Encode a shape into a canonical `ContractEmitted` payload AND the `Event`
/// the decoder should reconstruct from it.
fn encode_and_expect(shape: &EventShape) -> (Vec<u8>, Event) {
    match *shape {
        EventShape::Genesis { contract, admin, root, key } => {
            let mut data = Vec::with_capacity(64);
            data.extend_from_slice(&root);
            data.extend_from_slice(&key);
            let topics = vec![sig_genesis(), padded_address(admin)];
            let bytes = encode_contract_emitted(contract, data, topics);
            let expected = Event::Genesis {
                admin: OrgAdmin(admin),
                root_hash: OnChainRootHash(root),
                org_pub_key: OrgPubKey(key),
            };
            (bytes, expected)
        }
        EventShape::Update { contract, admin, epoch, root, key, prev_root } => {
            let mut data = Vec::with_capacity(96);
            data.extend_from_slice(&root);
            data.extend_from_slice(&key);
            data.extend_from_slice(&prev_root);
            let topics = vec![sig_root_updated(), padded_address(admin), uint256_be(epoch)];
            let bytes = encode_contract_emitted(contract, data, topics);
            let expected = Event::Update {
                admin: OrgAdmin(admin),
                epoch: Epoch(epoch),
                root_hash: OnChainRootHash(root),
                org_pub_key: OrgPubKey(key),
                prev_root_hash: OnChainRootHash(prev_root),
            };
            (bytes, expected)
        }
    }
}

fn main() {
    let decoder = for_runtime(PASEO_AH_SPEC_VERSION)
        .expect("pinned Paseo AH decoder must resolve");
    // AssertUnwindSafe for bolero's per-iteration catch_unwind (decoders are
    // stateless unit structs); deref inside the closure so the wrapper itself
    // is captured. The `dyn Decoder` receiver makes `use Decoder` unnecessary.
    let decoder = AssertUnwindSafe(decoder);
    check!()
        .with_type::<EventShape>()
        .cloned()
        .for_each(move |shape: EventShape| {
            let (bytes, expected) = encode_and_expect(&shape);
            let decoded = (*decoder)
                .parse_revive_event(&bytes)
                .expect("valid ContractEmitted payload must decode without error");
            assert_eq!(
                decoded,
                Some(expected),
                "decoder must invert the canonical encoding for {shape:?}",
            );
        });
}
